// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package biblAudio;

public final class ServeurIcePrxHelper extends Ice.ObjectPrxHelperBase implements ServeurIcePrx
{
    private static final String __afficherMorceaux_name = "afficherMorceaux";

    public void afficherMorceaux()
    {
        afficherMorceaux(null, false);
    }

    public void afficherMorceaux(java.util.Map<String, String> __ctx)
    {
        afficherMorceaux(__ctx, true);
    }

    private void afficherMorceaux(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_afficherMorceaux(begin_afficherMorceaux(__ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_afficherMorceaux()
    {
        return begin_afficherMorceaux(null, false, false, null);
    }

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx)
    {
        return begin_afficherMorceaux(__ctx, true, false, null);
    }

    public Ice.AsyncResult begin_afficherMorceaux(Ice.Callback __cb)
    {
        return begin_afficherMorceaux(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_afficherMorceaux(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_afficherMorceaux(Callback_ServeurIce_afficherMorceaux __cb)
    {
        return begin_afficherMorceaux(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, Callback_ServeurIce_afficherMorceaux __cb)
    {
        return begin_afficherMorceaux(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_afficherMorceaux(IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_afficherMorceaux(null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_afficherMorceaux(IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_afficherMorceaux(null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_afficherMorceaux(__ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_afficherMorceaux(__ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, 
                                                   boolean __explicitCtx, 
                                                   boolean __synchronous, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_afficherMorceaux(__ctx, 
                                      __explicitCtx, 
                                      __synchronous, 
                                      new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, 
                                                   boolean __explicitCtx, 
                                                   boolean __synchronous, 
                                                   IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__afficherMorceaux_name, __cb);
        try
        {
            __result.prepare(__afficherMorceaux_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            __result.writeEmptyParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_afficherMorceaux(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __afficherMorceaux_name);
    }

    private static final String __bAjoutMorceau_name = "bAjoutMorceau";

    public boolean bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie)
    {
        return bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, null, false);
    }

    public boolean bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx)
    {
        return bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, __ctx, true);
    }

    private boolean bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__bAjoutMorceau_name);
        return end_bAjoutMorceau(begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie)
    {
        return begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, null, false, false, null);
    }

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx)
    {
        return begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, Ice.Callback __cb)
    {
        return begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, Callback_ServeurIce_bAjoutMorceau __cb)
    {
        return begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx, Callback_ServeurIce_bAjoutMorceau __cb)
    {
        return begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                                String sNomMorc, 
                                                String sFic, 
                                                int uiDureeMorc, 
                                                int uiDateSortie, 
                                                java.util.Map<String, String> __ctx, 
                                                boolean __explicitCtx, 
                                                boolean __synchronous, 
                                                IceInternal.Functional_BoolCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_bAjoutMorceau(sNomArt, sNomMorc, sFic, uiDureeMorc, uiDateSortie, __ctx, __explicitCtx, __synchronous, 
                                   new IceInternal.Functional_TwowayCallbackBool(__responseCb, __exceptionCb, __sentCb)
                                       {
                                           public final void __completed(Ice.AsyncResult __result)
                                           {
                                               ServeurIcePrxHelper.__bAjoutMorceau_completed(this, __result);
                                           }
                                       });
    }

    private Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                                String sNomMorc, 
                                                String sFic, 
                                                int uiDureeMorc, 
                                                int uiDateSortie, 
                                                java.util.Map<String, String> __ctx, 
                                                boolean __explicitCtx, 
                                                boolean __synchronous, 
                                                IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__bAjoutMorceau_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__bAjoutMorceau_name, __cb);
        try
        {
            __result.prepare(__bAjoutMorceau_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(sNomArt);
            __os.writeString(sNomMorc);
            __os.writeString(sFic);
            __os.writeInt(uiDureeMorc);
            __os.writeInt(uiDateSortie);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public boolean end_bAjoutMorceau(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __bAjoutMorceau_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __bAjoutMorceau_completed(Ice.TwowayCallbackBool __cb, Ice.AsyncResult __result)
    {
        biblAudio.ServeurIcePrx __proxy = (biblAudio.ServeurIcePrx)__result.getProxy();
        boolean __ret = false;
        try
        {
            __ret = __proxy.end_bAjoutMorceau(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __bRechercherMorceau_name = "bRechercherMorceau";

    public Morceau bRechercherMorceau(String sNomMusique)
    {
        return bRechercherMorceau(sNomMusique, null, false);
    }

    public Morceau bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx)
    {
        return bRechercherMorceau(sNomMusique, __ctx, true);
    }

    private Morceau bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__bRechercherMorceau_name);
        return end_bRechercherMorceau(begin_bRechercherMorceau(sNomMusique, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique)
    {
        return begin_bRechercherMorceau(sNomMusique, null, false, false, null);
    }

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx)
    {
        return begin_bRechercherMorceau(sNomMusique, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, Ice.Callback __cb)
    {
        return begin_bRechercherMorceau(sNomMusique, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_bRechercherMorceau(sNomMusique, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, Callback_ServeurIce_bRechercherMorceau __cb)
    {
        return begin_bRechercherMorceau(sNomMusique, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx, Callback_ServeurIce_bRechercherMorceau __cb)
    {
        return begin_bRechercherMorceau(sNomMusique, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_bRechercherMorceau(sNomMusique, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_bRechercherMorceau(sNomMusique, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_bRechercherMorceau(sNomMusique, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_bRechercherMorceau(sNomMusique, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                     java.util.Map<String, String> __ctx, 
                                                     boolean __explicitCtx, 
                                                     boolean __synchronous, 
                                                     IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                     IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_bRechercherMorceau(sNomMusique, __ctx, __explicitCtx, __synchronous, 
                                        new IceInternal.Functional_TwowayCallbackArg1<biblAudio.Morceau>(__responseCb, __exceptionCb, __sentCb)
                                            {
                                                public final void __completed(Ice.AsyncResult __result)
                                                {
                                                    ServeurIcePrxHelper.__bRechercherMorceau_completed(this, __result);
                                                }
                                            });
    }

    private Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                     java.util.Map<String, String> __ctx, 
                                                     boolean __explicitCtx, 
                                                     boolean __synchronous, 
                                                     IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__bRechercherMorceau_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__bRechercherMorceau_name, __cb);
        try
        {
            __result.prepare(__bRechercherMorceau_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(sNomMusique);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public Morceau end_bRechercherMorceau(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __bRechercherMorceau_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            Morceau __ret = null;
            __ret = Morceau.__read(__is, __ret);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __bRechercherMorceau_completed(Ice.TwowayCallbackArg1<Morceau> __cb, Ice.AsyncResult __result)
    {
        biblAudio.ServeurIcePrx __proxy = (biblAudio.ServeurIcePrx)__result.getProxy();
        Morceau __ret = null;
        try
        {
            __ret = __proxy.end_bRechercherMorceau(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __bSuprMorceau_name = "bSuprMorceau";

    public boolean bSuprMorceau(String sNomMorc, String sNomArt)
    {
        return bSuprMorceau(sNomMorc, sNomArt, null, false);
    }

    public boolean bSuprMorceau(String sNomMorc, String sNomArt, java.util.Map<String, String> __ctx)
    {
        return bSuprMorceau(sNomMorc, sNomArt, __ctx, true);
    }

    private boolean bSuprMorceau(String sNomMorc, String sNomArt, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__bSuprMorceau_name);
        return end_bSuprMorceau(begin_bSuprMorceau(sNomMorc, sNomArt, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt)
    {
        return begin_bSuprMorceau(sNomMorc, sNomArt, null, false, false, null);
    }

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt, java.util.Map<String, String> __ctx)
    {
        return begin_bSuprMorceau(sNomMorc, sNomArt, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt, Ice.Callback __cb)
    {
        return begin_bSuprMorceau(sNomMorc, sNomArt, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_bSuprMorceau(sNomMorc, sNomArt, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt, Callback_ServeurIce_bSuprMorceau __cb)
    {
        return begin_bSuprMorceau(sNomMorc, sNomArt, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt, java.util.Map<String, String> __ctx, Callback_ServeurIce_bSuprMorceau __cb)
    {
        return begin_bSuprMorceau(sNomMorc, sNomArt, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              String sNomArt, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_bSuprMorceau(sNomMorc, sNomArt, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              String sNomArt, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_bSuprMorceau(sNomMorc, sNomArt, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              String sNomArt, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_bSuprMorceau(sNomMorc, sNomArt, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              String sNomArt, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_bSuprMorceau(sNomMorc, sNomArt, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                               String sNomArt, 
                                               java.util.Map<String, String> __ctx, 
                                               boolean __explicitCtx, 
                                               boolean __synchronous, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_bSuprMorceau(sNomMorc, sNomArt, __ctx, __explicitCtx, __synchronous, 
                                  new IceInternal.Functional_TwowayCallbackBool(__responseCb, __exceptionCb, __sentCb)
                                      {
                                          public final void __completed(Ice.AsyncResult __result)
                                          {
                                              ServeurIcePrxHelper.__bSuprMorceau_completed(this, __result);
                                          }
                                      });
    }

    private Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                               String sNomArt, 
                                               java.util.Map<String, String> __ctx, 
                                               boolean __explicitCtx, 
                                               boolean __synchronous, 
                                               IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__bSuprMorceau_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__bSuprMorceau_name, __cb);
        try
        {
            __result.prepare(__bSuprMorceau_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(sNomMorc);
            __os.writeString(sNomArt);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public boolean end_bSuprMorceau(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __bSuprMorceau_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __bSuprMorceau_completed(Ice.TwowayCallbackBool __cb, Ice.AsyncResult __result)
    {
        biblAudio.ServeurIcePrx __proxy = (biblAudio.ServeurIcePrx)__result.getProxy();
        boolean __ret = false;
        try
        {
            __ret = __proxy.end_bSuprMorceau(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __getMorceauxArt_name = "getMorceauxArt";

    public Morceau[] getMorceauxArt(String sNomArt)
    {
        return getMorceauxArt(sNomArt, null, false);
    }

    public Morceau[] getMorceauxArt(String sNomArt, java.util.Map<String, String> __ctx)
    {
        return getMorceauxArt(sNomArt, __ctx, true);
    }

    private Morceau[] getMorceauxArt(String sNomArt, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__getMorceauxArt_name);
        return end_getMorceauxArt(begin_getMorceauxArt(sNomArt, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt)
    {
        return begin_getMorceauxArt(sNomArt, null, false, false, null);
    }

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, java.util.Map<String, String> __ctx)
    {
        return begin_getMorceauxArt(sNomArt, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, Ice.Callback __cb)
    {
        return begin_getMorceauxArt(sNomArt, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getMorceauxArt(sNomArt, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, Callback_ServeurIce_getMorceauxArt __cb)
    {
        return begin_getMorceauxArt(sNomArt, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, java.util.Map<String, String> __ctx, Callback_ServeurIce_getMorceauxArt __cb)
    {
        return begin_getMorceauxArt(sNomArt, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, 
                                                IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_getMorceauxArt(sNomArt, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, 
                                                IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getMorceauxArt(sNomArt, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_getMorceauxArt(sNomArt, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getMorceauxArt(sNomArt, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_getMorceauxArt(String sNomArt, 
                                                 java.util.Map<String, String> __ctx, 
                                                 boolean __explicitCtx, 
                                                 boolean __synchronous, 
                                                 IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getMorceauxArt(sNomArt, __ctx, __explicitCtx, __synchronous, 
                                    new IceInternal.Functional_TwowayCallbackArg1<biblAudio.Morceau[]>(__responseCb, __exceptionCb, __sentCb)
                                        {
                                            public final void __completed(Ice.AsyncResult __result)
                                            {
                                                ServeurIcePrxHelper.__getMorceauxArt_completed(this, __result);
                                            }
                                        });
    }

    private Ice.AsyncResult begin_getMorceauxArt(String sNomArt, 
                                                 java.util.Map<String, String> __ctx, 
                                                 boolean __explicitCtx, 
                                                 boolean __synchronous, 
                                                 IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getMorceauxArt_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__getMorceauxArt_name, __cb);
        try
        {
            __result.prepare(__getMorceauxArt_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(sNomArt);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public Morceau[] end_getMorceauxArt(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __getMorceauxArt_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            Morceau[] __ret;
            __ret = mvectRechercheHelper.read(__is);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __getMorceauxArt_completed(Ice.TwowayCallbackArg1<Morceau[]> __cb, Ice.AsyncResult __result)
    {
        biblAudio.ServeurIcePrx __proxy = (biblAudio.ServeurIcePrx)__result.getProxy();
        Morceau[] __ret = null;
        try
        {
            __ret = __proxy.end_getMorceauxArt(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __getMorceauxMorc_name = "getMorceauxMorc";

    public Morceau[] getMorceauxMorc(String sNomMorc)
    {
        return getMorceauxMorc(sNomMorc, null, false);
    }

    public Morceau[] getMorceauxMorc(String sNomMorc, java.util.Map<String, String> __ctx)
    {
        return getMorceauxMorc(sNomMorc, __ctx, true);
    }

    private Morceau[] getMorceauxMorc(String sNomMorc, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__getMorceauxMorc_name);
        return end_getMorceauxMorc(begin_getMorceauxMorc(sNomMorc, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc)
    {
        return begin_getMorceauxMorc(sNomMorc, null, false, false, null);
    }

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, java.util.Map<String, String> __ctx)
    {
        return begin_getMorceauxMorc(sNomMorc, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, Ice.Callback __cb)
    {
        return begin_getMorceauxMorc(sNomMorc, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getMorceauxMorc(sNomMorc, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, Callback_ServeurIce_getMorceauxMorc __cb)
    {
        return begin_getMorceauxMorc(sNomMorc, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, java.util.Map<String, String> __ctx, Callback_ServeurIce_getMorceauxMorc __cb)
    {
        return begin_getMorceauxMorc(sNomMorc, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, 
                                                 IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_getMorceauxMorc(sNomMorc, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, 
                                                 IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getMorceauxMorc(sNomMorc, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_getMorceauxMorc(sNomMorc, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getMorceauxMorc(sNomMorc, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, 
                                                  java.util.Map<String, String> __ctx, 
                                                  boolean __explicitCtx, 
                                                  boolean __synchronous, 
                                                  IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getMorceauxMorc(sNomMorc, __ctx, __explicitCtx, __synchronous, 
                                     new IceInternal.Functional_TwowayCallbackArg1<biblAudio.Morceau[]>(__responseCb, __exceptionCb, __sentCb)
                                         {
                                             public final void __completed(Ice.AsyncResult __result)
                                             {
                                                 ServeurIcePrxHelper.__getMorceauxMorc_completed(this, __result);
                                             }
                                         });
    }

    private Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, 
                                                  java.util.Map<String, String> __ctx, 
                                                  boolean __explicitCtx, 
                                                  boolean __synchronous, 
                                                  IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getMorceauxMorc_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__getMorceauxMorc_name, __cb);
        try
        {
            __result.prepare(__getMorceauxMorc_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(sNomMorc);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public Morceau[] end_getMorceauxMorc(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __getMorceauxMorc_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            Morceau[] __ret;
            __ret = mvectRechercheHelper.read(__is);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __getMorceauxMorc_completed(Ice.TwowayCallbackArg1<Morceau[]> __cb, Ice.AsyncResult __result)
    {
        biblAudio.ServeurIcePrx __proxy = (biblAudio.ServeurIcePrx)__result.getProxy();
        Morceau[] __ret = null;
        try
        {
            __ret = __proxy.end_getMorceauxMorc(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __readSound_name = "readSound";

    public void readSound(String sNomMorceau, String sNomArtiste)
    {
        readSound(sNomMorceau, sNomArtiste, null, false);
    }

    public void readSound(String sNomMorceau, String sNomArtiste, java.util.Map<String, String> __ctx)
    {
        readSound(sNomMorceau, sNomArtiste, __ctx, true);
    }

    private void readSound(String sNomMorceau, String sNomArtiste, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_readSound(begin_readSound(sNomMorceau, sNomArtiste, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste)
    {
        return begin_readSound(sNomMorceau, sNomArtiste, null, false, false, null);
    }

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste, java.util.Map<String, String> __ctx)
    {
        return begin_readSound(sNomMorceau, sNomArtiste, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste, Ice.Callback __cb)
    {
        return begin_readSound(sNomMorceau, sNomArtiste, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_readSound(sNomMorceau, sNomArtiste, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste, Callback_ServeurIce_readSound __cb)
    {
        return begin_readSound(sNomMorceau, sNomArtiste, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste, java.util.Map<String, String> __ctx, Callback_ServeurIce_readSound __cb)
    {
        return begin_readSound(sNomMorceau, sNomArtiste, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_readSound(String sNomMorceau, 
                                           String sNomArtiste, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_readSound(sNomMorceau, sNomArtiste, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_readSound(String sNomMorceau, 
                                           String sNomArtiste, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_readSound(sNomMorceau, sNomArtiste, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_readSound(String sNomMorceau, 
                                           String sNomArtiste, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_readSound(sNomMorceau, sNomArtiste, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_readSound(String sNomMorceau, 
                                           String sNomArtiste, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_readSound(sNomMorceau, sNomArtiste, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_readSound(String sNomMorceau, 
                                            String sNomArtiste, 
                                            java.util.Map<String, String> __ctx, 
                                            boolean __explicitCtx, 
                                            boolean __synchronous, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_readSound(sNomMorceau, 
                               sNomArtiste, 
                               __ctx, 
                               __explicitCtx, 
                               __synchronous, 
                               new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_readSound(String sNomMorceau, 
                                            String sNomArtiste, 
                                            java.util.Map<String, String> __ctx, 
                                            boolean __explicitCtx, 
                                            boolean __synchronous, 
                                            IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__readSound_name, __cb);
        try
        {
            __result.prepare(__readSound_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(sNomMorceau);
            __os.writeString(sNomArtiste);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_readSound(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __readSound_name);
    }

    private static final String __readSoundFic_name = "readSoundFic";

    public void readSoundFic(String pathToFic)
    {
        readSoundFic(pathToFic, null, false);
    }

    public void readSoundFic(String pathToFic, java.util.Map<String, String> __ctx)
    {
        readSoundFic(pathToFic, __ctx, true);
    }

    private void readSoundFic(String pathToFic, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_readSoundFic(begin_readSoundFic(pathToFic, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_readSoundFic(String pathToFic)
    {
        return begin_readSoundFic(pathToFic, null, false, false, null);
    }

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, java.util.Map<String, String> __ctx)
    {
        return begin_readSoundFic(pathToFic, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, Ice.Callback __cb)
    {
        return begin_readSoundFic(pathToFic, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_readSoundFic(pathToFic, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, Callback_ServeurIce_readSoundFic __cb)
    {
        return begin_readSoundFic(pathToFic, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, java.util.Map<String, String> __ctx, Callback_ServeurIce_readSoundFic __cb)
    {
        return begin_readSoundFic(pathToFic, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_readSoundFic(pathToFic, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_readSoundFic(pathToFic, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_readSoundFic(pathToFic, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_readSoundFic(pathToFic, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_readSoundFic(String pathToFic, 
                                               java.util.Map<String, String> __ctx, 
                                               boolean __explicitCtx, 
                                               boolean __synchronous, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_readSoundFic(pathToFic, 
                                  __ctx, 
                                  __explicitCtx, 
                                  __synchronous, 
                                  new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_readSoundFic(String pathToFic, 
                                               java.util.Map<String, String> __ctx, 
                                               boolean __explicitCtx, 
                                               boolean __synchronous, 
                                               IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__readSoundFic_name, __cb);
        try
        {
            __result.prepare(__readSoundFic_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(pathToFic);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_readSoundFic(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __readSoundFic_name);
    }

    private static final String __stopSound_name = "stopSound";

    public void stopSound()
    {
        stopSound(null, false);
    }

    public void stopSound(java.util.Map<String, String> __ctx)
    {
        stopSound(__ctx, true);
    }

    private void stopSound(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_stopSound(begin_stopSound(__ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_stopSound()
    {
        return begin_stopSound(null, false, false, null);
    }

    public Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx)
    {
        return begin_stopSound(__ctx, true, false, null);
    }

    public Ice.AsyncResult begin_stopSound(Ice.Callback __cb)
    {
        return begin_stopSound(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_stopSound(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_stopSound(Callback_ServeurIce_stopSound __cb)
    {
        return begin_stopSound(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx, Callback_ServeurIce_stopSound __cb)
    {
        return begin_stopSound(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_stopSound(IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_stopSound(null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_stopSound(IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_stopSound(null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_stopSound(__ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_stopSound(__ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx, 
                                            boolean __explicitCtx, 
                                            boolean __synchronous, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_stopSound(__ctx, 
                               __explicitCtx, 
                               __synchronous, 
                               new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx, 
                                            boolean __explicitCtx, 
                                            boolean __synchronous, 
                                            IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__stopSound_name, __cb);
        try
        {
            __result.prepare(__stopSound_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            __result.writeEmptyParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_stopSound(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __stopSound_name);
    }

    public static ServeurIcePrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), ServeurIcePrx.class, ServeurIcePrxHelper.class);
    }

    public static ServeurIcePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), ServeurIcePrx.class, ServeurIcePrxHelper.class);
    }

    public static ServeurIcePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), ServeurIcePrx.class, ServeurIcePrxHelper.class);
    }

    public static ServeurIcePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), ServeurIcePrx.class, ServeurIcePrxHelper.class);
    }

    public static ServeurIcePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, ServeurIcePrx.class, ServeurIcePrxHelper.class);
    }

    public static ServeurIcePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, ServeurIcePrx.class, ServeurIcePrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::biblAudio::ServeurIce"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, ServeurIcePrx v)
    {
        __os.writeProxy(v);
    }

    public static ServeurIcePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            ServeurIcePrxHelper result = new ServeurIcePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
