// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package biblAudio;

public interface ServeurIce extends Ice.Object,
                                    _ServeurIceOperations, _ServeurIceOperationsNC
{
    public static final String ice_staticId = "::biblAudio::ServeurIce";

    public static final long serialVersionUID = -7336562591879936527L;
}
