// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package biblAudio;

public final class mmapMorceauxHolder extends Ice.Holder<java.util.Map<java.lang.String, Morceau>>
{
    public
    mmapMorceauxHolder()
    {
    }

    public
    mmapMorceauxHolder(java.util.Map<java.lang.String, Morceau> value)
    {
        super(value);
    }
}
