// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package biblAudio;

public interface MonitorPrx extends Ice.ObjectPrx
{
    public void report(String action, Morceau morceau);

    public void report(String action, Morceau morceau, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_report(String action, Morceau morceau);

    public Ice.AsyncResult begin_report(String action, Morceau morceau, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_report(String action, Morceau morceau, Ice.Callback __cb);

    public Ice.AsyncResult begin_report(String action, Morceau morceau, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_report(String action, Morceau morceau, Callback_Monitor_report __cb);

    public Ice.AsyncResult begin_report(String action, Morceau morceau, java.util.Map<String, String> __ctx, Callback_Monitor_report __cb);

    public Ice.AsyncResult begin_report(String action, 
                                        Morceau morceau, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_report(String action, 
                                        Morceau morceau, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_report(String action, 
                                        Morceau morceau, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_report(String action, 
                                        Morceau morceau, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_report(Ice.AsyncResult __result);
}
