// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package biblAudio;

public final class MonitorPrxHelper extends Ice.ObjectPrxHelperBase implements MonitorPrx
{
    private static final String __report_name = "report";

    public void report(String action, Morceau morceau)
    {
        report(action, morceau, null, false);
    }

    public void report(String action, Morceau morceau, java.util.Map<String, String> __ctx)
    {
        report(action, morceau, __ctx, true);
    }

    private void report(String action, Morceau morceau, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_report(begin_report(action, morceau, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_report(String action, Morceau morceau)
    {
        return begin_report(action, morceau, null, false, false, null);
    }

    public Ice.AsyncResult begin_report(String action, Morceau morceau, java.util.Map<String, String> __ctx)
    {
        return begin_report(action, morceau, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_report(String action, Morceau morceau, Ice.Callback __cb)
    {
        return begin_report(action, morceau, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_report(String action, Morceau morceau, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_report(action, morceau, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_report(String action, Morceau morceau, Callback_Monitor_report __cb)
    {
        return begin_report(action, morceau, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_report(String action, Morceau morceau, java.util.Map<String, String> __ctx, Callback_Monitor_report __cb)
    {
        return begin_report(action, morceau, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_report(String action, 
                                        Morceau morceau, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_report(action, morceau, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_report(String action, 
                                        Morceau morceau, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_report(action, morceau, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_report(String action, 
                                        Morceau morceau, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_report(action, morceau, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_report(String action, 
                                        Morceau morceau, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_report(action, morceau, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_report(String action, 
                                         Morceau morceau, 
                                         java.util.Map<String, String> __ctx, 
                                         boolean __explicitCtx, 
                                         boolean __synchronous, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_report(action, 
                            morceau, 
                            __ctx, 
                            __explicitCtx, 
                            __synchronous, 
                            new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_report(String action, 
                                         Morceau morceau, 
                                         java.util.Map<String, String> __ctx, 
                                         boolean __explicitCtx, 
                                         boolean __synchronous, 
                                         IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__report_name, __cb);
        try
        {
            __result.prepare(__report_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(action);
            Morceau.__write(__os, morceau);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_report(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __report_name);
    }

    public static MonitorPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), MonitorPrx.class, MonitorPrxHelper.class);
    }

    public static MonitorPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), MonitorPrx.class, MonitorPrxHelper.class);
    }

    public static MonitorPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), MonitorPrx.class, MonitorPrxHelper.class);
    }

    public static MonitorPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), MonitorPrx.class, MonitorPrxHelper.class);
    }

    public static MonitorPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, MonitorPrx.class, MonitorPrxHelper.class);
    }

    public static MonitorPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, MonitorPrx.class, MonitorPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::biblAudio::Monitor"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, MonitorPrx v)
    {
        __os.writeProxy(v);
    }

    public static MonitorPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            MonitorPrxHelper result = new MonitorPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
