// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package biblAudio;

public interface ServeurIcePrx extends Ice.ObjectPrx
{
    public void afficherMorceaux();

    public void afficherMorceaux(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_afficherMorceaux();

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_afficherMorceaux(Ice.Callback __cb);

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_afficherMorceaux(Callback_ServeurIce_afficherMorceaux __cb);

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, Callback_ServeurIce_afficherMorceaux __cb);

    public Ice.AsyncResult begin_afficherMorceaux(IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_afficherMorceaux(IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public void end_afficherMorceaux(Ice.AsyncResult __result);

    public Morceau bRechercherMorceau(String sNomMusique);

    public Morceau bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, Ice.Callback __cb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, Callback_ServeurIce_bRechercherMorceau __cb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx, Callback_ServeurIce_bRechercherMorceau __cb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public Morceau end_bRechercherMorceau(Ice.AsyncResult __result);

    public boolean bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie);

    public boolean bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, Ice.Callback __cb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, Callback_ServeurIce_bAjoutMorceau __cb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx, Callback_ServeurIce_bAjoutMorceau __cb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_bAjoutMorceau(Ice.AsyncResult __result);

    public boolean bSuprMorceau(String sNomMorc, String sNomArt);

    public boolean bSuprMorceau(String sNomMorc, String sNomArt, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt, Ice.Callback __cb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt, Callback_ServeurIce_bSuprMorceau __cb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, String sNomArt, java.util.Map<String, String> __ctx, Callback_ServeurIce_bSuprMorceau __cb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              String sNomArt, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              String sNomArt, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              String sNomArt, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              String sNomArt, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_bSuprMorceau(Ice.AsyncResult __result);

    public Morceau[] getMorceauxArt(String sNomArt);

    public Morceau[] getMorceauxArt(String sNomArt, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt);

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, Callback_ServeurIce_getMorceauxArt __cb);

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, java.util.Map<String, String> __ctx, Callback_ServeurIce_getMorceauxArt __cb);

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, 
                                                IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, 
                                                IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getMorceauxArt(String sNomArt, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Morceau[] end_getMorceauxArt(Ice.AsyncResult __result);

    public Morceau[] getMorceauxMorc(String sNomMorc);

    public Morceau[] getMorceauxMorc(String sNomMorc, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc);

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, Callback_ServeurIce_getMorceauxMorc __cb);

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, java.util.Map<String, String> __ctx, Callback_ServeurIce_getMorceauxMorc __cb);

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, 
                                                 IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, 
                                                 IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getMorceauxMorc(String sNomMorc, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Morceau[] end_getMorceauxMorc(Ice.AsyncResult __result);

    public void stopSound();

    public void stopSound(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopSound();

    public Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopSound(Ice.Callback __cb);

    public Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopSound(Callback_ServeurIce_stopSound __cb);

    public Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx, Callback_ServeurIce_stopSound __cb);

    public Ice.AsyncResult begin_stopSound(IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_stopSound(IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_stopSound(java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public void end_stopSound(Ice.AsyncResult __result);

    public void readSoundFic(String pathToFic);

    public void readSoundFic(String pathToFic, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_readSoundFic(String pathToFic);

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, Ice.Callback __cb);

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, Callback_ServeurIce_readSoundFic __cb);

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, java.util.Map<String, String> __ctx, Callback_ServeurIce_readSoundFic __cb);

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_readSoundFic(String pathToFic, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public void end_readSoundFic(Ice.AsyncResult __result);

    public void readSound(String sNomMorceau, String sNomArtiste);

    public void readSound(String sNomMorceau, String sNomArtiste, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste);

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste, Ice.Callback __cb);

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste, Callback_ServeurIce_readSound __cb);

    public Ice.AsyncResult begin_readSound(String sNomMorceau, String sNomArtiste, java.util.Map<String, String> __ctx, Callback_ServeurIce_readSound __cb);

    public Ice.AsyncResult begin_readSound(String sNomMorceau, 
                                           String sNomArtiste, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_readSound(String sNomMorceau, 
                                           String sNomArtiste, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_readSound(String sNomMorceau, 
                                           String sNomArtiste, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_readSound(String sNomMorceau, 
                                           String sNomArtiste, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public void end_readSound(Ice.AsyncResult __result);
}
